version: '3.8'

services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - toshiro_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - toshiro_net
    deploy:
      replicas: 1

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - toshiro_net
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db_data:

networks:
  toshiro_net:
    driver: overlay
